name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::464004139021:role/GithubActionsRole
          aws-region: us-east-1

      - 
        name: Display Identity
        run: aws sts get-caller-identity 

      - 
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - 
      #   name: Create and Display ECR Repo
      #   run: aws ecr create-repository --repoistory-name ???

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Build, tag and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE: oooooooo
          TAG: latest
        run: |
          docker buildx build -t $ECR_REGISTRY/$IMAGE:$TAG ../../code/discordlambda/ -f ./Dockerfile
          docker push $ECR_REGISTRY/$IMAGE:$TAG
    #   -
    #     name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    #   -
    #     name: Build and push
    #     uses: docker/build-push-action@v5
    #     with:
    #       push: true
    #       tags: user/app:latest